version: "3"

services:
  node_server:
    container_name: nodeServer
    image: 'nginx:1.21.3-alpine'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '3005:80'